### PR TITLE
CpuidIterator: Better identifies the last sub-leaf

### PR DESCRIPTION
**Pull request by andrewjj20**
There is no one definition of what is the last sub-leaf. It must be determined by looking at what each leaf definition is. This may become more complicated as more are added.

### CODE REVIEW

**Comment by cmouzaoui** [comment]
What's the connection between this change to the checks on these registers `e[a-d]x` and identifying the last subleaf?

**Comment by andrewjj20** [comment]
There are multiple ways (2) to discover the end sub-leaf depending on the leaf that is being requested. These are both of the 2, there does not seem like there is a way for them to overlap.

**Comment by andrewjj20** [comment]
basically, finding decent guidlines on where the subleaves end involves looking over the intel software developer's manual and trying to find all the ways for them to show that the area past the end has been hit.

**Review by cmouzaoui — APPROVED** [review]
According to the convo in the comments, I'm assuming that this code better identifies the last sub-leaf because "the Intel manual says so"

**Pull request merged**
